# Generated by Django 2.2.5 on 2020-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdataset',
            name='folder',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='appdataset',
            name='file_name',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
