# Generated by Django 2.2.5 on 2020-12-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeldSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_code', models.CharField(max_length=32, null=True)),
                ('app_test_status', models.NullBooleanField()),
                ('app_inspector_code', models.CharField(default='', max_length=32, null=True)),
                ('app_defect_type', models.CharField(default='', max_length=32, null=True)),
                ('app_test_result', models.CharField(default='', max_length=16, null=True)),
                ('app_test_notes', models.TextField(default='', null=True)),
                ('ray_test_status', models.NullBooleanField()),
                ('ray_inspector_code', models.CharField(default='', max_length=32, null=True)),
                ('ray_defect_type', models.CharField(default='', max_length=32, null=True)),
                ('ray_test_result', models.CharField(default='', max_length=16, null=True)),
                ('ray_test_notes', models.TextField(default='', null=True)),
                ('app_defect_type_0', models.NullBooleanField()),
                ('app_defect_type_1', models.NullBooleanField()),
                ('app_defect_type_2', models.NullBooleanField()),
                ('app_defect_type_3', models.NullBooleanField()),
                ('app_defect_type_4', models.NullBooleanField()),
                ('app_defect_type_5', models.NullBooleanField()),
                ('task_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_manage.Task')),
            ],
        ),
    ]
